# Generated by Django 5.2.12 on 2026-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roleassignment',
            new_name='accounts_ro_role_989ac9_idx',
            old_name='accounts_ro_role_3be4af_idx',
        ),
    ]
