# Generated by Django 5.2.12 on 2026-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_story_sync_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adosprintsnapshot',
            new_name='integration_source__5056b0_idx',
            old_name='integ_src_ext_7f9ef6_idx',
        ),
        migrations.RenameIndex(
            model_name='adouserstory',
            new_name='integration_is_acti_6ee744_idx',
            old_name='ado_story_act_sprint_idx',
        ),
        migrations.RenameIndex(
            model_name='adouserstory',
            new_name='integration_work_it_d04d8d_idx',
            old_name='ado_story_wi_idx',
        ),
        migrations.RenameIndex(
            model_name='adouserstory',
            new_name='integration_state_6cc8e0_idx',
            old_name='ado_story_state_idx',
        ),
        migrations.RenameIndex(
            model_name='azurewritebackrequest',
            new_name='integration_status_72b55c_idx',
            old_name='ado_write_status_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationsyncstate',
            new_name='integration_key_c1096a_idx',
            old_name='integ_sync_key_23dd2e_idx',
        ),
    ]
