# Generated by Django 5.2.12 on 2026-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vendoraction',
            new_name='vendor_queu_status_9ce118_idx',
            old_name='vendor_queu_status_8cfde2_idx',
        ),
    ]
