# Generated by Django 5.2.12 on 2026-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0002_manual_ticket_assignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='manualticketassignment',
            new_name='mappings_ma_assignm_ab8e74_idx',
            old_name='manual_assign_mode_idx',
        ),
        migrations.RenameIndex(
            model_name='releasesprintmapping',
            new_name='mappings_re_mapping_c66012_idx',
            old_name='mappings_re_mappin_03666f_idx',
        ),
    ]
