# Generated by Django 5.2.12 on 2026-04-04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("verification_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("unsubscribe_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("requested_by_display_name", models.CharField(blank=True, max_length=120)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["email"],
                "indexes": [models.Index(fields=["is_verified", "is_active"], name="status_repo_is_verif_13abcc_idx")],
            },
        ),
        migrations.CreateModel(
            name="StatusReportItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("owner_name", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("in_progress", "In Progress"), ("action_required", "Action Required"), ("on_hold", "On Hold"), ("completed", "Completed"), ("canceled", "Canceled")], default="in_progress", max_length=24)),
                ("order_index", models.PositiveIntegerField(default=100)),
                ("updated_by_display_name", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["order_index", "due_date", "id"],
                "indexes": [models.Index(fields=["status", "due_date"], name="status_repo_status_49711e_idx")],
            },
        ),
    ]
