# Generated by Django 5.2.12 on 2026-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mismatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mismatchfinding',
            new_name='mismatch_mi_status_a992e8_idx',
            old_name='mismatch_mi_status_e4c34f_idx',
        ),
        migrations.RenameIndex(
            model_name='mismatchfinding',
            new_name='mismatch_mi_finding_dbe85b_idx',
            old_name='mismatch_mi_finding_26c57b_idx',
        ),
    ]
