# Generated by Django 5.2.12 on 2026-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_entity__0bff9a_idx',
            old_name='audit_audit_entity__6a495a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_0c0ad1_idx',
            old_name='audit_audit_action_6cc27d_idx',
        ),
    ]
